services:
  nats:
    image: nats:alpine
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["streaming"]
networks:
  streaming: